package uz.zero.auth.enums


enum class ErrorCode(val code: Int) {
    VALIDATION_ERROR(40),
    ROLE_KEY_ALREADY_EXISTS(100),
    PERMISSION_GROUP_NOT_FOUND(101),
    ROLE_NOT_FOUND(102),
    ROLE_HAS_RELATION_WITH_USER(103),
    PERMISSION_GROUP_KEY_ALREADY_EXISTS(104),
    PERMISSION_KEY_ALREADY_EXIST(105),
    PERMISSION_NOT_FOUND(106),
    ROLE_LEVEL_BIGGER_THAN_YOURS(107),
    USERNAME_ALREADY_TAKEN(108),
    USER_NOT_FOUND(109),
    USER_UPDATE_NOT_ALLOWED(110),
    CLIENT_ALREADY_EXISTS(111),
    CLIENT_NOT_FOUND(112),
    PARTNER_NOT_FOUND(113),
}